CREATE TABLE ADMINISTRACION(
	ID INT,
	ID_PERSONA INT,
	USUARIO VARCHAR(100),
	PASSWORD VARCHAR(100),
	FECHA_CREACION DATETIME,
	
)
CREATE TABLE UNIDADES(
	ID INT,
	ID_MARCA INT,
	ID_MODELO INT,
	PATENTE VARCHAR(100),
	VENCIMIENTO_VTV DATETIME,
	VENCIMIENTO_SEGURO DATETIME,
	FECHA_CREACION DATETIME,
	ID_ESTADO INT
)
CREATE TABLE CARGAS_COMBUSTIBLES(
	ID INT,
	DESCRIPCION VARCHAR(100),
	MONTO FLOAT,
	FECHA_CREACION DATETIME
)
CREATE TABLE CHOFER(
	ID INT,
	ID_PERSONA INT,
	FECHA_CREACION DATETIME,
	ID_ESTADO INT
)
CREATE TABLE CHOFER_POR_AUTO(
	ID INT,
	ID_CHOFER INT,
	ID_AUTO INT,
	FECHA_CREACION DATETIME,
)
CREATE TABLE CLIENTE(
	ID INT,
	ID_PERSONA INT,
	CODIGO VARCHAR(100),
	FECHA_CREACION DATETIME
)
CREATE TABLE DUEÑO(
	ID INT,
	ID_PERSONA INT,
	FECHA_CREACION DATETIME
)
CREATE TABLE ESTADOS_UNIDADES(
	ID INT,
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION DATETIME
)
CREATE TABLE ESTADOS_CHOFER(
	ID INT,
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION DATETIME 
)
CREATE TABLE ESTADOS_CHOFER_POR_AUTO(
	ID INT,
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION DATETIME 
)
CREATE TABLE ESTADOS_RESERVA(
	ID INT,
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION DATETIME 
)
CREATE TABLE ESTADOS_VIAJE(
	ID INT,
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION DATETIME 
)
CREATE TABLE MARCA(
	ID INT,
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION DATETIME 
)
CREATE TABLE MODELOS(
	ID INT,
	ID_MARCA INT,
	DESCRIPCION VARCHAR(100),
	FECHA_CREACION DATETIME 
)
CREATE TABLE PERSONAS(
	ID INT,
	NOMBRE VARCHAR(100),
	APELLIDO VARCHAR(100),
	DNI VARCHAR(10),
	DOMICILIO VARCHAR(255),
	CALLE VARCHAR(100),
	TELEFONO VARCHAR(100),
	CELULAR VARCHAR(100),
	FECHA_CREACION DATETIME
)
CREATE TABLE RENDICION(
	ID INT,
	ID_ADMINISTRACION INT,
	ID_CHOFER_POR_AUTO INT,
	FECHA_INICIO DATETIME,
	FECHA_CIERRE DATETIME,
	FECHA_CREACION DATETIME
)
CREATE TABLE RESERVAS_DIARIAS(
	ID INT,
	ID_CLIENTE INT,
	ID_DIA INT,
	ID_ADMINISTRADOR INT,
	FECHA_CREACION DATETIME,
	ID_ESTADO INT
)
CREATE TABLE VIAJES(
	ID INT,
	ID_CHOFER_POR_AUTO INT,
	ID_ADMINISTRACION INT,
	ORIGEN VARCHAR(100),
	DESTINO VARCHAR(100),
	VALOR_KILOMETRO FLOAT,
	VALOR_ESTIMADO FLOAT,
	FECHA_CREACION DATETIME,
	ID_ESTADO INT
)